manage.py loaddata disease.yaml
manage.py loaddata group.yaml
manage.py loaddata dental_office.yaml
manage.py loaddata tooth.yaml
manage.py loaddata insurance.yaml
manage.py loaddata appointment_type.yaml
manage.py loaddata user.yaml
manage.py loaddata patient.yaml
manage.py loaddata patient_diseases.yaml
manage.py loaddata dentist.yaml
manage.py loaddata password_creation.yaml
manage.py loaddata tooth_part.yaml
manage.py loaddata loss_type.yaml